export const pizzas = [
    {
        name: "Italian",
        type: "Meat",
        ingredients: ["onion", "potato", "tomato", "mushrooms", "cheese", "olives", "meat"],
        price: 8.35,
        image: "img/pizzas/pizza_img_1.png",
        rating: 8.5,
    },
    {
        name: "Venecia",
        type: "Vegetarian",
        ingredients: ["onion", "potato", "tomato", "mushrooms", "cheese", "olives"],
        price: 7.35,
        image: "img/pizzas/pizza_img_2.png",
        rating: 9.3,
    },
    {
        name: "Meat",
        type: "Meat",
        ingredients: ["tomato sauce", "onion", "bell pepper", "mozzarella", "beef", "salami"],
        price: 9.35,
        image: "img/pizzas/pizza_img_3.png",
        rating: 7.8,
    },
    {
        name: "Cheese",
        type: "Vegetarian",
        ingredients: ["mozzarella", "cheddar", "parmesan", "gorgonzola", "tomato"],
        price: 8.35,
        image: "img/pizzas/pizza_img_4.png",
        rating: 8.9,
    },
    {
        name: "Seafood",
        type: "Sea products",
        ingredients: ["tomato sauce", "mozzarella", "shrimp", "squid", "garlic", "olive oil"],
        price: 10.95,
        image: "img/pizzas/pizza_img_5.png",
        rating: 7.3,
    },
    {
        name: "Mushrooms",
        type: "Mushroom",
        ingredients: ["mushrooms", "mozzarella", "white sauce", "onion", "parsley"],
        price: 8.95,
        image: "img/pizzas/pizza_img_6.png",
        rating: 6.8,
    },
    {
        name: "Pepperoni",
        type: "Meat",
        ingredients: ["tomato sauce", "mozzarella", "pepperoni", "oregano"],
        price: 9.75,
        image: "img/pizzas/pizza_img_7.png",
        rating: 9.2,
    },
    {
        name: "Hawaiian",
        type: "Meat",
        ingredients: ["tomato sauce", "mozzarella", "ham", "pineapple", "cheese"],
        price: 9.15,
        image: "img/pizzas/pizza_img_8.png",
        rating: 7.1,
    },
    // --- NEW 12 ---
    {
        name: "Diablo",
        type: "Meat",
        ingredients: ["spicy salami", "jalapeno", "mozzarella", "chili oil"],
        price: 9.85,
        image: "img/pizzas/pizza_img_1.png",
        rating: 9.1,
    },
    {
        name: "Truffle Deluxe",
        type: "Mushroom",
        ingredients: ["truffle oil", "mushrooms", "mozzarella", "white sauce"],
        price: 10.25,
        image: "img/pizzas/pizza_img_6.png",
        rating: 8.7,
    },
    {
        name: "Capricciosa",
        type: "Meat",
        ingredients: ["ham", "artichokes", "mushrooms", "olives", "tomato sauce"],
        price: 9.50,
        image: "img/pizzas/pizza_img_2.png",
        rating: 8.3,
    },
    {
        name: "Veggie Garden",
        type: "Vegetarian",
        ingredients: ["zucchini", "eggplant", "onion", "bell pepper", "mozzarella"],
        price: 8.20,
        image: "img/pizzas/pizza_img_4.png",
        rating: 7.9,
    },
    {
        name: "Carbonara",
        type: "Meat",
        ingredients: ["bacon", "egg sauce", "mozzarella", "parmesan"],
        price: 9.60,
        image: "img/pizzas/pizza_img_3.png",
        rating: 8.8,
    },
    {
        name: "Shrimp Lover",
        type: "Sea products",
        ingredients: ["shrimp", "mozzarella", "garlic butter", "parsley"],
        price: 11.10,
        image: "img/pizzas/pizza_img_5.png",
        rating: 8.1,
    },
    {
        name: "Forest Mushroom",
        type: "Mushroom",
        ingredients: ["wild mushrooms", "cream sauce", "onion", "cheese"],
        price: 8.80,
        image: "img/pizzas/pizza_img_6.png",
        rating: 8.0,
    },
    {
        name: "Four Seasons",
        type: "Vegetarian",
        ingredients: ["mozzarella", "tomato", "artichokes", "olives", "mushrooms"],
        price: 8.90,
        image: "img/pizzas/pizza_img_4.png",
        rating: 9.0,
    },
    {
        name: "Salmon Deluxe",
        type: "Sea products",
        ingredients: ["salmon", "mozzarella", "cream", "dill"],
        price: 11.50,
        image: "img/pizzas/pizza_img_5.png",
        rating: 9.4,
    },
    {
        name: "BBQ Chicken",
        type: "Meat",
        ingredients: ["chicken", "bbq sauce", "red onion", "mozzarella"],
        price: 9.80,
        image: "img/pizzas/pizza_img_7.png",
        rating: 9.0,
    },
    {
        name: "Spinach Ricotta",
        type: "Vegetarian",
        ingredients: ["spinach", "ricotta", "mozzarella", "white sauce"],
        price: 8.60,
        image: "img/pizzas/pizza_img_2.png",
        rating: 8.2,
    },
    {
        name: "Tropical Mix",
        type: "Meat",
        ingredients: ["ham", "pineapple", "sweet corn", "mozzarella"],
        price: 9.10,
        image: "img/pizzas/pizza_img_8.png",
        rating: 7.6,
    },
    {
        name: "Greek Style",
        type: "Vegetarian",
        ingredients: ["feta cheese", "olives", "tomato", "oregano", "olive oil"],
        price: 8.40,
        image: "img/pizzas/pizza_img_3.png",
        rating: 8.5,
    },
];

export const ingredients = [
    "onion",
    "potato",
    "tomato",
    "mushrooms",
    "cheese",
    "olives",
    "meat",
    "tomato sauce",
    "bell pepper",
    "mozzarella",
    "beef",
    "salami",
    "cheddar",
    "parmesan",
    "gorgonzola",
    "shrimp",
    "squid",
    "garlic",
    "olive oil",
    "white sauce",
    "parsley",
    "pepperoni",
    "oregano",
    "ham",
    "pineapple",
    "spicy salami",
    "jalapeno",
    "chili oil",
    "truffle oil",
    "artichokes",
    "zucchini",
    "eggplant",
    "bacon",
    "egg sauce",
    "garlic butter",
    "wild mushrooms",
    "cream",
    "dill",
    "chicken",
    "bbq sauce",
    "red onion",
    "spinach",
    "ricotta",
    "sweet corn",
    "feta cheese"
];